In [1]:
from pathlib import Path

data_path = Path("../data/raw/MedQuAD")

for path in data_path.rglob("*"):
    print(path)

..\data\raw\MedQuAD\.git
..\data\raw\MedQuAD\10_MPlus_ADAM_QA
..\data\raw\MedQuAD\11_MPlusDrugs_QA
..\data\raw\MedQuAD\12_MPlusHerbsSupplements_QA
..\data\raw\MedQuAD\1_CancerGov_QA
..\data\raw\MedQuAD\2_GARD_QA
..\data\raw\MedQuAD\3_GHR_QA
..\data\raw\MedQuAD\4_MPlus_Health_Topics_QA
..\data\raw\MedQuAD\5_NIDDK_QA
..\data\raw\MedQuAD\6_NINDS_QA
..\data\raw\MedQuAD\7_SeniorHealth_QA
..\data\raw\MedQuAD\8_NHLBI_QA_XML
..\data\raw\MedQuAD\9_CDC_QA
..\data\raw\MedQuAD\LICENSE.txt
..\data\raw\MedQuAD\QA-TestSet-LiveQA-Med-Qrels-2479-Answers.zip
..\data\raw\MedQuAD\readme.txt
..\data\raw\MedQuAD\.git\config
..\data\raw\MedQuAD\.git\description
..\data\raw\MedQuAD\.git\HEAD
..\data\raw\MedQuAD\.git\hooks
..\data\raw\MedQuAD\.git\index
..\data\raw\MedQuAD\.git\info
..\data\raw\MedQuAD\.git\logs
..\data\raw\MedQuAD\.git\objects
..\data\raw\MedQuAD\.git\packed-refs
..\data\raw\MedQuAD\.git\refs
..\data\raw\MedQuAD\.git\hooks\applypatch-msg.sample
..\data\raw\MedQuAD\.git\hooks\commit-msg.sample
..\data\raw\MedQuAD\.git\hooks\fsmonitor-watchman.sample
..\data\raw\MedQuAD\.git\hooks\post-update.sample
..\data\raw\MedQuAD\.git\hooks\pre-applypatch.sample
..\data\raw\MedQuAD\.git\hooks\pre-commit.sample
..\data\raw\MedQuAD\.git\hooks\pre-merge-commit.sample
..\data\raw\MedQuAD\.git\hooks\pre-push.sample
..\data\raw\MedQuAD\.git\hooks\pre-rebase.sample
..\data\raw\MedQuAD\.git\hooks\pre-receive.sample
..\data\raw\MedQuAD\.git\hooks\prepare-commit-msg.sample
..\data\raw\MedQuAD\.git\hooks\push-to-checkout.sample
..\data\raw\MedQuAD\.git\hooks\sendemail-validate.sample
..\data\raw\MedQuAD\.git\hooks\update.sample
..\data\raw\MedQuAD\.git\info\exclude
..\data\raw\MedQuAD\.git\logs\HEAD
..\data\raw\MedQuAD\.git\logs\refs
..\data\raw\MedQuAD\.git\logs\refs\heads
..\data\raw\MedQuAD\.git\logs\refs\remotes
..\data\raw\MedQuAD\.git\logs\refs\heads\master
..\data\raw\MedQuAD\.git\logs\refs\remotes\origin
..\data\raw\MedQuAD\.git\logs\refs\remotes\origin\HEAD
..\data\raw\MedQuAD\.git\objects\info
..\data\raw\MedQuAD\.git\objects\pack
..\data\raw\MedQuAD\.git\objects\pack\pack-3d889fc356c501ddd370cf933d512ade2bc0d40c.idx
..\data\raw\MedQuAD\.git\objects\pack\pack-3d889fc356c501ddd370cf933d512ade2bc0d40c.pack
..\data\raw\MedQuAD\.git\objects\pack\pack-3d889fc356c501ddd370cf933d512ade2bc0d40c.rev
..\data\raw\MedQuAD\.git\refs\heads
..\data\raw\MedQuAD\.git\refs\remotes
..\data\raw\MedQuAD\.git\refs\tags
..\data\raw\MedQuAD\.git\refs\heads\master
..\data\raw\MedQuAD\.git\refs\remotes\origin
..\data\raw\MedQuAD\.git\refs\remotes\origin\HEAD
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000001.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000002.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000003.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000004.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000005.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000006.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000007.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000008.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000009.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000010.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000011.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000012.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000013.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000014.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000015.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000016.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000017.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000018.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000019.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000020.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000021.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000022.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000023.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000024.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000025.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000026.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000027.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000028.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000029.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000030.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000031.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000032.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000033.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000034.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000035.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000036.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000037.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000038.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000039.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000040.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000041.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000042.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000043.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000044.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000045.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000046.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000047.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000048.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000049.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000050.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000051.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000052.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000053.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000054.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000055.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000056.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000057.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000058.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000059.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000060.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000061.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000062.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000063.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000064.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000065.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000066.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000067.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000068.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000069.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000070.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000071.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000072.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000073.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000074.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000075.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000076.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000077.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000078.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000079.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000080.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000081.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000082.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000083.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000084.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000085.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000086.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000087.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000088.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000089.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000090.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000091.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000092.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000093.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000094.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000095.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000096.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000097.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000098.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000099.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000100.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000101.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000102.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000103.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000104.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000105.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000106.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000107.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000108.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000109.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000110.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000111.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000112.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000113.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000114.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000115.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000116.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000117.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000118.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000119.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000120.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000121.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000122.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000123.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000124.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000125.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000126.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000127.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000128.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000129.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000130.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000131.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000132.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000133.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000134.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000135.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000136.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000137.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000138.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000139.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000140.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000141.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000142.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000143.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000144.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000145.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000146.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000147.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000148.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000149.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000150.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000151.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000152.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000153.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000154.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000155.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000156.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000157.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000158.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000159.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000160.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000161.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000162.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000163.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000164.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000165.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000166.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000167.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000168.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000169.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000170.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000171.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000172.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000173.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000174.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000175.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000176.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000177.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000178.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000179.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000180.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000181.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000182.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000183.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000184.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000185.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000186.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000187.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000188.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000189.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000190.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000191.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000192.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000193.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000194.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000195.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000196.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000197.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000198.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000199.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000200.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000201.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000202.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000203.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000204.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000205.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000206.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000207.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000208.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000209.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000210.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000211.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000212.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000213.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000214.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000215.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000216.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000217.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000218.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000219.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000220.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000221.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000222.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000223.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000224.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000225.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000226.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000227.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000228.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000229.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000230.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000231.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000232.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000233.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000234.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000235.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000236.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000237.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000238.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000239.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000240.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000241.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000242.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000243.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000244.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000245.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000246.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000247.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000248.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000249.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000250.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000251.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000252.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000253.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000254.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000255.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000256.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000257.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000258.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000259.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000260.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000261.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000262.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000263.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000264.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000265.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000266.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000267.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000268.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000269.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000270.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000271.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000272.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000273.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000274.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000275.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000276.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000277.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000278.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000279.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000280.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000281.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000282.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000283.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000284.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000285.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000286.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000287.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000288.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000289.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000290.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000291.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000292.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000293.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000294.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000295.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000296.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000297.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000298.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000299.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000300.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000301.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000302.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000303.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000304.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000305.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000306.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000307.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000308.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000309.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000310.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000311.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000312.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000313.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000314.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000315.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000316.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000317.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000318.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000319.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000320.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000321.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000322.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000323.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000324.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000325.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000326.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000327.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000328.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000329.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000330.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000331.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000332.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000333.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000334.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000335.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000336.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000337.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000338.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000339.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000340.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000341.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000342.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000343.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000344.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000345.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000346.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000347.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000348.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000349.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000350.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000351.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000352.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000353.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000354.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000355.xml

In [2]:
xml_files = list(data_path.rglob("*.xml"))

print("Number of XML files:", len(xml_files))

for file in xml_files[:10]:
    print(file)

Number of XML files: 11274
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000001.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000002.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000003.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000004.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000005.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000006.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000007.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000008.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000009.xml
..\data\raw\MedQuAD\10_MPlus_ADAM_QA\0000010.xml

In [3]:
from pathlib import Path

xml_file = xml_files[0]

print(xml_file.read_text(encoding="utf-8")[:5000])

<?xml version="1.0" encoding="UTF-8"?>
<Document id="0000001" source="ADAM" url="https://www.nlm.nih.gov/medlineplus/ency/patientinstructions/000823.htm">
 <!--Answers from the A.D.A.M. medical encyclopedia were removed to comply with the MedlinePlus copyright-->
<Focus>A guide to clinical trials for cancer</Focus>
<FocusAnnotations>
	<Category>Disease</Category>
	<UMLS>
		<CUIs>
			<CUI>C0006826</CUI>
		</CUIs>
		<SemanticTypes>
			<SemanticType>T191</SemanticType>
		</SemanticTypes>
		<SemanticGroup>Disorders</SemanticGroup>
	</UMLS>
	<Synonyms>
		<Synonym>Intervention study</Synonym>
	</Synonyms>
</FocusAnnotations>
<QAPairs>
	<QAPair pid="1">
			<Question qid="0000001-1" qtype="information">What is (are) A guide to clinical trials for cancer ?</Question>
			<Answer></Answer>
	</QAPair>
	<QAPair pid="2">
			<Question qid="0000001-2" qtype="research">what research (or clinical trials) is being done for A guide to clinical trials for cancer ?</Question>
			<Answer></Answer>
	</QAPair>
	<QAPair pid="3">
			<Question qid="0000001-3" qtype="research">what research (or clinical trials) is being done for A guide to clinical trials for cancer ?</Question>
			<Answer></Answer>
	</QAPair>
	<QAPair pid="6">
			<Question qid="0000001-6" qtype="research">what research (or clinical trials) is being done for A guide to clinical trials for cancer ?</Question>
			<Answer></Answer>
	</QAPair>
	<QAPair pid="7">
			<Question qid="0000001-7" qtype="research">what research (or clinical trials) is being done for A guide to clinical trials for cancer ?</Question>
			<Answer></Answer>
	</QAPair>
</QAPairs>
</Document>

In [4]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/clinical_knowledge.csv"
)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 16359
Columns: 12

In [5]:
df.columns.tolist()

['document_id',
 'qid',
 'source',
 'url',
 'focus',
 'category',
 'umls_cui',
 'semantic_group',
 'synonyms',
 'question',
 'question_type',
 'answer']

In [6]:
pd.set_option("display.max_colwidth", 300)

df.iloc[0]

document_id                                                                                                                                                                                                                                                                                                         0000001_1
qid                                                                                                                                                                                                                                                                                                               0000001_1-1
source                                                                                                                                                                                                                                                                                                              CancerGov
url                                                                                                                                                                                                                                                     https://www.cancer.gov/types/leukemia/patient/adult-all-treatment-pdq
focus                                                                                                                                                                                                                                                                                      Adult Acute Lymphoblastic Leukemia
category                                                                                                                                                                                                                                                                                                                  NaN
umls_cui                                                                                                                                                                                                                                                                                                             C0751606
semantic_group                                                                                                                                                                                                                                                                                                      Disorders
synonyms                                                                                                                                                                                                                                                                                                                  NaN
question                                                                                                                                                                                                                                                                   What is (are) Adult Acute Lymphoblastic Leukemia ?
question_type                                                                                                                                                                                                                                                                                                     information
answer            Key Points\n                    - Adult acute lymphoblastic leukemia (ALL) is a type of cancer in which the bone marrow makes too many lymphocytes (a type of white blood cell).    - Leukemia may affect red blood cells, white blood cells, and platelets.    - Previous chemotherapy and exposure to ...
Name: 0, dtype: str

In [7]:
pd.set_option("display.max_colwidth", 300)

df.iloc[0]

document_id                                                                                                                                                                                                                                                                                                         0000001_1
qid                                                                                                                                                                                                                                                                                                               0000001_1-1
source                                                                                                                                                                                                                                                                                                              CancerGov
url                                                                                                                                                                                                                                                     https://www.cancer.gov/types/leukemia/patient/adult-all-treatment-pdq
focus                                                                                                                                                                                                                                                                                      Adult Acute Lymphoblastic Leukemia
category                                                                                                                                                                                                                                                                                                                  NaN
umls_cui                                                                                                                                                                                                                                                                                                             C0751606
semantic_group                                                                                                                                                                                                                                                                                                      Disorders
synonyms                                                                                                                                                                                                                                                                                                                  NaN
question                                                                                                                                                                                                                                                                   What is (are) Adult Acute Lymphoblastic Leukemia ?
question_type                                                                                                                                                                                                                                                                                                     information
answer            Key Points\n                    - Adult acute lymphoblastic leukemia (ALL) is a type of cancer in which the bone marrow makes too many lymphocytes (a type of white blood cell).    - Leukemia may affect red blood cells, white blood cells, and platelets.    - Previous chemotherapy and exposure to ...
Name: 0, dtype: str

In [8]:
df["question_type"].value_counts()

question_type
information        4520
symptoms           2747
treatment          2440
inheritance        1446
frequency          1120
genetic changes    1087
causes              708
exams and tests     650
research            395
outlook             361
susceptibility      324
considerations      228
prevention          209
stages               77
complications        46
support groups        1
Name: count, dtype: int64

In [9]:
df["category"].value_counts().head(20)

category
Disease    686
Other      295
Name: count, dtype: int64

In [10]:
df["source"].value_counts()

source
GHR                  5430
GARD                 5389
NIDDK                1144
NINDS                1088
MPlusHealthTopics     981
NIHSeniorHealth       769
CancerGov             729
NHLBI                 559
CDC                   270
Name: count, dtype: int64

In [11]:
df.isnull().sum()

document_id           5
qid                   0
source                0
url                   0
focus                14
category          15378
umls_cui            565
semantic_group      565
synonyms           5469
question              0
question_type         0
answer                0
dtype: int64

In [12]:
print(
    "Duplicate questions:",
    df["question"].duplicated().sum()
)

Duplicate questions: 1380

In [13]:
df["question_words"] = df["question"].str.split().str.len()
df["answer_words"] = df["answer"].str.split().str.len()

df[["question_words", "answer_words"]].describe()

       question_words  answer_words
count    16359.000000  16359.000000
mean         8.214561    200.366587
std          2.381010    246.873458
min          3.000000      1.000000
25%          6.000000     71.000000
50%          8.000000    138.000000
75%         10.000000    251.000000
max         27.000000   4281.000000

In [14]:
duplicate_questions = (
    df[df["question"].duplicated(keep=False)]
    .sort_values("question")
)

duplicate_questions[
    ["question", "answer", "source"]
].head(20)

,question,answer,source
12543,How to diagnose Adrenal Insufficiency and Addison's Disease ?,"After Addisons disease is diagnosed, health care providers may use the following tests to look at the adrenal glands, find out whether the disease is related to TB, or identify antibodies associated with autoimmune Addisons disease.\n \n- Ultrasound of the abdomen. Ultrasound uses...",NIDDK
12542,How to diagnose Adrenal Insufficiency and Addison's Disease ?,"In its early stages, adrenal insufficiency can be difficult to diagnose. A health care provider may suspect it after reviewing a persons medical history and symptoms.\n \nA diagnosis of adrenal insufficiency is confirmed through hormonal blood and urine tests. A health care provid...",NIDDK
14792,How to diagnose Alzheimer's Caregiving ?,"Now that your family member or friend has received a diagnosis of Alzheimers disease, its important to learn as much as you can about the disease and how to care for someone who has it. You may also want to know the right way to share the news with family and friends. Learning About Alzheimers S...",NIHSeniorHealth
14798,How to diagnose Alzheimer's Caregiving ?,"When you learn that someone has Alzheimers disease, you may wonder when and how to tell your family and friends. You may be worried about how others will react to or treat the person. Others often sense that something is wrong before they are told. Alzheimers disease is hard to keep secret. When...",NIHSeniorHealth
14816,How to diagnose Alzheimer's Disease ?,"The only definitive way to diagnose Alzheimer's disease is to find out whether plaques and tangles exist in brain tissue. To look at brain tissue, doctors perform a brain autopsy, an examination of the brain done after a person dies. Doctors can only make a diagnosis of ""possible"" or probable Al...",NIHSeniorHealth
14817,How to diagnose Alzheimer's Disease ?,"An early, accurate diagnosis of Alzheimer's disease helps people and their families plan for the future. It gives them time to discuss care options, find support, and make legal and financial arrangements while the person with Alzheimers can still take part in making decisions. Also, even though...",NIHSeniorHealth
14818,How to diagnose Alzheimer's Disease ?,The time from diagnosis of Alzheimers disease to death varies. It can be as little as 3 or 4 years if the person is over 80 years old when diagnosed or as long as 10 years or more if the person is younger.,NIHSeniorHealth
13106,How to diagnose Amyloidosis and Kidney Disease ?,A health care provider diagnoses primary amyloidosis of the kidneys with\n \n- a medical and family history - a physical exam - urinalysis - blood tests - a kidney biopsy\n \nMedical and Family History\n \nTaking a medical and family history may h...,NIDDK
13107,How to diagnose Amyloidosis and Kidney Disease ?,"A health care provider diagnoses dialysis-related amyloidosis with\n \n- urinalysis - blood tests - imaging tests\n \nA health care provider can use urinalysis and blood tests to detect the amount of amyloid proteins in urine and blood. Imaging tests, such as x-ra...",NIDDK
562,How to diagnose Breast Cancer ?,"Breast exams should be part of prenatal and postnatal care.\n\t\t To detect breast cancer, pregnant and nursing women should examine their breasts themselves. Women should also receive clinical breast exams during their regular prenatal and postnatal check-ups. Talk to your do...",CancerGov
14859,How to diagnose Breast Cancer ?,"Most cancers in their early, most treatable stages do not cause any symptoms. That is why it's important to have regular tests to check for cancer long before you might notice anything wrong. Detecting Breast Cancer Through Screening When breast cancer is found early, it is more likely to be tre...",NIHSeniorHealth
546,How to diagnose Breast Cancer ?,Tests that examine the breasts are used to detect (find) and diagnose breast cancer.\n Check with your doctor if you notice any changes in your breasts. The following tests and procedures may be used: - Physical exam and history : An exam of the body to check general...,CancerGov
14931,How to diagnose COPD ?,"If you have not been exercising regularly, you should get the advice of your doctor before starting. The symptoms of COPD are different for each person. People with mild COPD may not have much difficulty walking or exercising. As the symptoms of COPD get worse over time, a person may have more d...",NIHSeniorHealth
14929,How to diagnose COPD ?,"To confirm a COPD diagnosis, a doctor will use a breathing test called spirometry. The test is easy and painless. It shows how well the lungs are working. The spirometer measures how much air the lungs can hold and how fast air is blown out of the lungs. Other tests, such as bronchodilator rever...",NIHSeniorHealth
12784,How to diagnose Celiac Disease ?,"In some cases, a health care provider will order genetic blood tests to confirm or rule out a diagnosis of celiac disease. Most people with celiac disease have gene pairs that contain at least one of the human leukocyte antigen (HLA) gene variants.4 However, these variants are also common in peo...",NIDDK
12783,How to diagnose Celiac Disease ?,A health care provider diagnoses celiac disease with\n \n- a medical and family history - a physical exam - blood tests - an intestinal biopsy - a skin biopsy\n \nMedical and Family History\n \nTaking a medical and family history may help a health...,NIDDK
14947,How to diagnose Creating a Family Health History ?,"Finding out your test results can affect you emotionally. Learning that you are someone in your family has or is at risk for a disease can be scary. Some people can also feel guilty, angry, anxious, or depressed when they find out their results. Covering the costs of testing can also be a challe...",NIHSeniorHealth
14946,How to diagnose Creating a Family Health History ?,"Genetic testing may be helpful whether the test identifies a mutation or not. Test results can - serve as a relief, eliminating some of the uncertainty about a health condition - help doctors make recommendations for treatment or monitoring - give people information to use in making decisions...",NIHSeniorHealth
12664,How to diagnose Diabetic Kidney Disease ?,A health care provider diagnoses diabetic kidney disease based on\n \n- a medical and family history - a physical exam - urine tests - a blood test\n \nMedical and Family History\n \nTaking a medical and family history is one of the first things a ...,NIDDK
12665,How to diagnose Diabetic Kidney Disease ?,People with diabetes should get regular screenings for kidney disease. The National Kidney Disease Education Program recommends the following:\n \n- urine albumin-to-creatinine ratio measured at least once a year in all people with type 2 diabetes and people who have had type 1 di...,NIDDK

In [16]:
import pandas as pd

rag_df = pd.read_csv(
    "../data/processed/rag_documents.csv"
)

print("Rows:", rag_df.shape[0])
print("Columns:", rag_df.shape[1])

rag_df.head()

Rows: 16359
Columns: 9

,document_id,qid,rag_text,source,url,focus,question_type,umls_cui,semantic_group
0,0000001_1,0000001_1-1,Topic: Adult Acute Lymphoblastic Leukemia\n\nQuestion: What is (are) Adult Acute Lymphoblastic Leukemia?\n\nAnswer: Key Points - Adult acute lymphoblastic leukemia (ALL) is a type of cancer in which the bone marrow makes too many lymphocytes (a type of white blood cell). - Leukemia may affect re...,CancerGov,https://www.cancer.gov/types/leukemia/patient/adult-all-treatment-pdq,Adult Acute Lymphoblastic Leukemia,information,C0751606,Disorders
1,0000001_1,0000001_1-2,"Topic: Adult Acute Lymphoblastic Leukemia\n\nQuestion: What are the symptoms of Adult Acute Lymphoblastic Leukemia?\n\nAnswer: Signs and symptoms of adult ALL include fever, feeling tired, and easy bruising or bleeding. The early signs and symptoms of ALL may be like the flu or other common dise...",CancerGov,https://www.cancer.gov/types/leukemia/patient/adult-all-treatment-pdq,Adult Acute Lymphoblastic Leukemia,symptoms,C0751606,Disorders
2,0000001_1,0000001_1-3,Topic: Adult Acute Lymphoblastic Leukemia\n\nQuestion: How to diagnose Adult Acute Lymphoblastic Leukemia?\n\nAnswer: Tests that examine the blood and bone marrow are used to detect (find) and diagnose adult ALL. The following tests and procedures may be used: - Physical exam and history: An exa...,CancerGov,https://www.cancer.gov/types/leukemia/patient/adult-all-treatment-pdq,Adult Acute Lymphoblastic Leukemia,exams and tests,C0751606,Disorders
3,0000001_1,0000001_1-4,Topic: Adult Acute Lymphoblastic Leukemia\n\nQuestion: What is the outlook for Adult Acute Lymphoblastic Leukemia?\n\nAnswer: Certain factors affect prognosis (chance of recovery) and treatment options. The prognosis (chance of recovery) and treatment options depend on the following: - The age o...,CancerGov,https://www.cancer.gov/types/leukemia/patient/adult-all-treatment-pdq,Adult Acute Lymphoblastic Leukemia,outlook,C0751606,Disorders
4,0000001_1,0000001_1-5,Topic: Adult Acute Lymphoblastic Leukemia\n\nQuestion: Who is at risk for Adult Acute Lymphoblastic Leukemia??\n\nAnswer: Previous chemotherapy and exposure to radiation may increase the risk of developing ALL. Anything that increases your risk of getting a disease is called a risk factor. Havin...,CancerGov,https://www.cancer.gov/types/leukemia/patient/adult-all-treatment-pdq,Adult Acute Lymphoblastic Leukemia,susceptibility,C0751606,Disorders

In [17]:
print(rag_df["rag_text"].iloc[0])

Topic: Adult Acute Lymphoblastic Leukemia

Question: What is (are) Adult Acute Lymphoblastic Leukemia?

Answer: Key Points - Adult acute lymphoblastic leukemia (ALL) is a type of cancer in which the bone marrow makes too many lymphocytes (a type of white blood cell). - Leukemia may affect red blood cells, white blood cells, and platelets. - Previous chemotherapy and exposure to radiation may increase the risk of developing ALL. - Signs and symptoms of adult ALL include fever, feeling tired, and easy bruising or bleeding. - Tests that examine the blood and bone marrow are used to detect (find) and diagnose adult ALL. - Certain factors affect prognosis (chance of recovery) and treatment options. Adult acute lymphoblastic leukemia (ALL) is a type of cancer in which the bone marrow makes too many lymphocytes (a type of white blood cell). Adult acute lymphoblastic leukemia (ALL; also called acute lymphocytic leukemia) is a cancer of the blood and bone marrow. This type of cancer usually gets worse quickly if it is not treated. Leukemia may affect red blood cells, white blood cells, and platelets. Normally, the bone marrow makes blood stem cells (immature cells) that become mature blood cells over time. A blood stem cell may become a myeloid stem cell or a lymphoid stem cell. A myeloid stem cell becomes one of three types of mature blood cells: - Red blood cells that carry oxygen and other substances to all tissues of the body. - Platelets that form blood clots to stop bleeding. - Granulocytes (white blood cells) that fight infection and disease. A lymphoid stem cell becomes a lymphoblast cell and then one of three types of lymphocytes (white blood cells): - B lymphocytes that make antibodies to help fight infection. - T lymphocytes that help B lymphocytes make the antibodies that help fight infection. - Natural killer cells that attack cancer cells and viruses. In ALL, too many stem cells become lymphoblasts, B lymphocytes, or T lymphocytes. These cells are also called leukemia cells. These leukemia cells are not able to fight infection very well. Also, as the number of leukemia cells increases in the blood and bone marrow, there is less room for healthy white blood cells, red blood cells, and platelets. This may cause infection, anemia, and easy bleeding. The cancer can also spread to the central nervous system (brain and spinal cord). This summary is about adult acute lymphoblastic leukemia. See the following PDQ summaries for information about other types of leukemia: - Childhood Acute Lymphoblastic Leukemia Treatment. - Adult Acute Myeloid Leukemia Treatment. - Childhood Acute Myeloid Leukemia/Other Myeloid Malignancies Treatment. - Chronic Lymphocytic Leukemia Treatment. - Chronic Myelogenous Leukemia Treatment. - Hairy Cell Leukemia Treatment.

In [18]:
longest_idx = rag_df["rag_text"].str.len().idxmax()

print(rag_df.loc[longest_idx, "rag_text"])

Topic: Breast Cancer

Question: What are the treatments for Breast Cancer?
